const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync('csv-data.js', 'utf8'), ctx);
const parks = fs.readFileSync('data/lekplatser.csv', 'utf8');
const checks = fs.readFileSync('data/kontrollpunkter.csv', 'utf8');
const config = ctx.buildConfiguration(parks, checks);
assert.equal(config.parks.length, 4);
assert.equal(Object.keys(config.featureTypes).length, 4);
assert.deepEqual([...config.parks[0].featureIds], ['Gångbro', 'Skulptur', 'Lekhus']);
assert.equal(config.featureTypes['Skulptur'].points.length, 3);
assert.equal(config.featureTypes['Gångbro'].pointIds[0], 'kp-01');
assert.equal(ctx.parseCsv('\uFEFFId,Namn\r\n1,"Text, med ""citat""\nand ny rad"\r\n')[1][1], 'Text, med "citat"\nand ny rad');
assert.equal(ctx.buildConfiguration(parks.replaceAll(';', ','), checks.replaceAll(';', ',')).parks.length, 4);
assert.equal(ctx.buildConfiguration(parks.replaceAll('X', 'x'), checks).parks.length, 4);
assert.throws(() => ctx.buildConfiguration(parks.replace(';X;', ';Ja;'), checks), /Använd X/);
assert.throws(() => ctx.buildConfiguration(parks, checks.replace('Gångbro', 'Bro')), /samma namn/);
assert.throws(() => ctx.buildConfiguration(parks.replace('lekplats-02', 'lekplats-01'), checks), /dubbla/);
assert.throws(() => ctx.buildConfiguration(parks.replace('lekplats-01', '__proto__'), checks), /Lekplats-ID/);
assert.throws(() => ctx.buildConfiguration(parks, checks.replace('kp-02', 'kp-01')), /dubbla/);
assert.throws(() => ctx.buildConfiguration(parks, checks.replaceAll(';X', ';')), /saknar kontrollpunkter/);
assert.throws(() => ctx.parseCsv('Id;Namn\n1;"utan avslut'), /saknar avslutning/);
assert.throws(() => ctx.parseCsv('Id;Namn\n1;namn;extra'), /antal kolumner/);
console.log('Passed: CSV mappings, UTF-8 BOM, commas/semicolons, quotes, multiline cells, lowercase x, invalid markers, mismatched types, duplicate IDs, unsafe IDs, empty forms, malformed CSV.');
